[package]
name = "retailer-sourcing"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "retailer-sourcing"
path = "src/bin/retailer-sourcing.rs"

[[bin]]
name = "migrate"
path = "src/bin/migrate.rs"

[[bin]]
name = "process-inbox"
path = "src/bin/process_inbox.rs"

[[bin]]
name = "process-commands"
path = "src/bin/process_commands.rs"

[[bin]]
name = "process-events"
path = "src/bin/process_events.rs"

[[bin]]
name = "process-outbox"
path = "src/bin/process_outbox.rs"

[[bin]]
name = "entry-error-tracing"
path = "src/bin/entry_error_tracing.rs"

[[bin]]
name = "truncate-dev"
path = "src/bin/truncate_dev.rs"

[[bin]]
name = "truncate-test"
path = "src/bin/truncate_test.rs"

[dependencies]
diesel = { version = "2", features = ["postgres", "r2d2", "uuid"] }
diesel_migrations = "2"
dotenvy = "0.15"
kernel = { version = "0.2.0", registry = "margo", default-features = false, package = "mulac-kernel" }
lapin = "4.5.0"
outbox = { version = "0.2.0", registry = "margo", default-features = false, features = ["diesel", "amqp"], package = "mulac-outbox" }
retailer-guild = { path = "../../lib/retailer-guild" }

poem = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
subtle = "2"
thiserror = "2"
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v7", "serde"] }

[dev-dependencies]
poem = { version = "3", features = ["test"] }
serial_test = "3"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
