[package]
name = "retailer-sourcing"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "retailer-sourcing"
path = "src/bin/retailer-sourcing.rs"

[dependencies]
commanding = { git = "https://github.com/nulllabsdev/mulac.git" }
eventing = { git = "https://github.com/nulllabsdev/mulac.git" }
inbox = { git = "https://github.com/nulllabsdev/mulac.git" }
mulac_diesel = { git = "https://github.com/nulllabsdev/mulac.git" }
outbox = { git = "https://github.com/nulllabsdev/mulac.git" }
poem = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
